export const LOGIN_LOADING = "LOGIN_LOADING";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS" ;
export const LOGIN_FAIL = "LOGIN_FAIL";

export const REGISTER_LOADING = "REGISTER_LOADING";
export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const REGISTER_FAIL = 'REGISTER_FAIL';
export const USER_PRESENT = "USER_PRESENT"

export const TRACKER_SUCCESS = "TRACKER_SUCCESS";
export const TRACKER_FAIL = "TRACKER_FAIL";

export const TRANSACTION_SUCCESS = "TRANSACTION_SUCCESS";
export const TRANSACTION_FAIL = "TRANSACTION_FAIL";

export const DELETE_TRANSACTION = "DELETE_TRANSACTION";

export const UPDATE_TRANSACTION = "UPDATE_TRANSACTION";

